#pragma once

#define VND_POOL_TAG 'VndP'

#define VND_DEVICE_TYPE 0x8000
#define IOCTL_VND_REGISTER_PROCESS \
    CTL_CODE(VND_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VND_UNREGISTER_PROCESS \
	CTL_CODE(VND_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VND_CREATE_MAPPING \
    CTL_CODE(VND_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VND_UPDATE_GLOBAL_MAP \
    CTL_CODE(VND_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VND_UPDATE_PROCESS_MAP \
    CTL_CODE(VND_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VND_GET_FLAG \
    CTL_CODE(VND_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define FLAG_LEN 36

typedef struct _VND_DEVICE_EXTENSION
{
	LIST_ENTRY ProcessMetaDataListHead;
}VND_DEVICE_EXTENSION, * PVND_DEVICE_EXTENSION;

typedef struct _VND_USER_PROCESS
{
	PVOID pSharedMapData;
	ULONG ulMetadataSize;
	CHAR Metadata[1];
}VND_USER_PROCESS, * PVND_USER_PROCESS;

typedef struct _VND_PROCESS
{
	LIST_ENTRY ListEntry;
	HANDLE Pid;
	BOOLEAN bRegistered;
	BOOLEAN bIsLeet;
	PMDL pSharedMapMdl;
	PVOID pSharedMap;
	ULONG ulMetadataSize;
	CHAR Metadata[1];
}VND_PROCESS, * PVND_PROCESS;
